/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messagerie.GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import myconnections.DBConnection;

/**
 *
 * @author alanl
 */
public class BoiteRecep extends javax.swing.JPanel {

    /**
     * Creates new form BoiteRecep
     */
    int id = MenuEmp.idemp;
    public BoiteRecep() throws SQLException {
        initComponents();
        boite_reception(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msgReçus = new javax.swing.JTextArea();
        btRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 255));
        setLayout(new java.awt.BorderLayout());

        msgReçus.setBackground(new java.awt.Color(51, 51, 51));
        msgReçus.setColumns(20);
        msgReçus.setForeground(new java.awt.Color(255, 255, 255));
        msgReçus.setLineWrap(true);
        msgReçus.setRows(20);
        msgReçus.setTabSize(50);
        jScrollPane1.setViewportView(msgReçus);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btRetour.setBackground(new java.awt.Color(51, 51, 51));
        btRetour.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btRetour.setForeground(new java.awt.Color(204, 204, 0));
        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        add(btRetour, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        Fenetre.f.setContentPane(new MenuEmp2());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRetour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgReçus;
    // End of variables declaration//GEN-END:variables
    
    private void boite_reception(int id) throws SQLException {
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.exit(1);
        }
        String c = "", date = "", nom, prenom, msgs = "";
        int ide;
        int flag = 0;
        String query = "select * from infos where idemp = ? order by idmsg desc";
        String query2 = "update infos set datelecture = sysdate where idemp = ? and datelecture is null";
        String query3 = "select * from message where idmsg = ?";
        String query4 = "select prenom, nom from employe where idemp = ?";
        try (PreparedStatement pstm = dbConnect.prepareStatement(query);PreparedStatement pstm2 = dbConnect.prepareStatement(query2);PreparedStatement pstm3 = dbConnect.prepareStatement(query3);PreparedStatement pstm4 = dbConnect.prepareStatement(query4)) {
            pstm.setInt(1, id);
            pstm2.setInt(1, id);
            pstm2.executeUpdate();
            try (ResultSet rs = pstm.executeQuery()) {  
                    while(rs.next()){
                        flag = 1;
                        int idmsg2 = rs.getInt("IDMSG"); 
                        pstm3.setInt(1, idmsg2);
                        ResultSet rs3 = pstm3.executeQuery();
                        rs3.next();
                        c = rs3.getString("CONTENU");
                        date = rs3.getString("DATEENVOI");
                        ide = rs3.getInt("IDEMP");
                        pstm4.setInt(1, ide);
                        ResultSet rs4 = pstm4.executeQuery();
                        rs4.next();
                        nom = rs4.getString("NOM");
                        prenom = rs4.getString("PRENOM");
                        msgs = msgs+c+"\nenvoyé le "+date+" par "+prenom+" "+nom+"\n\n";
                    }
                if(flag == 1){
                    msgReçus.setText(msgs);
                }
                else {
                    throw new SQLException("Code inconnu");
                }                
            }
        } 
    }
}
