/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messagerie.GUI;

/**
 *
 * @author alanl
 */
public class ChoixRechercheEmp extends javax.swing.JPanel {

    /**
     * Creates new form ChoixRechercheEmp
     */
    public ChoixRechercheEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btId = new javax.swing.JButton();
        btNom = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new java.awt.GridLayout(4, 1, 20, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quelle recherche ?");
        add(jLabel1);

        btId.setBackground(new java.awt.Color(51, 51, 51));
        btId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btId.setForeground(new java.awt.Color(255, 255, 255));
        btId.setText("Par id");
        btId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIdActionPerformed(evt);
            }
        });
        add(btId);

        btNom.setBackground(new java.awt.Color(51, 51, 51));
        btNom.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btNom.setForeground(new java.awt.Color(255, 255, 255));
        btNom.setText("Par nom/prénom");
        btNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNomActionPerformed(evt);
            }
        });
        add(btNom);

        btRetour.setBackground(new java.awt.Color(51, 51, 51));
        btRetour.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btRetour.setForeground(new java.awt.Color(255, 255, 255));
        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        add(btRetour);
    }// </editor-fold>//GEN-END:initComponents

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        Fenetre.f.setContentPane(new MenuGestEmp());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed

    private void btIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIdActionPerformed
        Fenetre.f.setContentPane(new ReadEmploye());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btIdActionPerformed

    private void btNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNomActionPerformed
        Fenetre.f.setContentPane(new ReadEmploye2());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btNomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btId;
    private javax.swing.JButton btNom;
    private javax.swing.JButton btRetour;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
