/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messagerie.GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import messagerie.Bureau;
import messagerie.DAO.BureauDAO;
import myconnections.DBConnection;

/**
 *
 * @author alanl
 */
public class DeleteBureau extends javax.swing.JPanel {

    /**
     * Creates new form DeleteBureau
     */
    
    String sigle, tel; 
    
    public DeleteBureau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        btId = new javax.swing.JButton();
        btConf = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 204));
        setLayout(new java.awt.GridLayout(5, 1, 20, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrez l'id du bureau à supprimer");
        add(jLabel1);

        tfId.setBackground(new java.awt.Color(255, 255, 255));
        tfId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfId.setForeground(new java.awt.Color(0, 0, 0));
        tfId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIdKeyTyped(evt);
            }
        });
        add(tfId);

        btId.setBackground(new java.awt.Color(51, 51, 51));
        btId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btId.setForeground(new java.awt.Color(255, 255, 255));
        btId.setText("Voir les id");
        btId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIdActionPerformed(evt);
            }
        });
        add(btId);

        btConf.setBackground(new java.awt.Color(51, 51, 51));
        btConf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btConf.setForeground(new java.awt.Color(255, 255, 255));
        btConf.setText("Confirmer");
        btConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfActionPerformed(evt);
            }
        });
        add(btConf);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Fenetre.f.setContentPane(new MenuGestBur());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfActionPerformed
        String id = tfId.getText();
        String liste = "";
        if(id.equals("")){
            JOptionPane.showMessageDialog(this,"Vous n'avez entré aucun id !","Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try{
                BureauDAO bdao = new BureauDAO();
                int idb = Integer.parseInt(id);
                ResultSet rs, rs2;
                Statement stmt, stmt2;
                int flag = 0;
                Connection dbConnect = DBConnection.getConnection();
                if (dbConnect == null) {
                    System.exit(1);
                }
                stmt = dbConnect.createStatement();
                rs = stmt.executeQuery("select * from bureau");
                while(rs.next()){
                    if(idb == rs.getInt("IDBUR")){
                        stmt2 = dbConnect.createStatement();
                        rs2 = stmt2.executeQuery("select * from employe");
                        while(rs2.next()){
                            if(rs2.getInt("IDBUR") == idb){
                                liste = liste + "\n" + rs2.getString("PRENOM") + " " + rs2.getString("NOM");
                                flag = 1;
                            }
                        }
                        if(liste.equals("")){
                            flag = 2;
                        }
                        break;
                    }
                }
                switch (flag) {
                    case 0:
                        JOptionPane.showMessageDialog(this,"L'id entré ne correspond à aucun bureau !","Erreur",JOptionPane.INFORMATION_MESSAGE);
                        break;
                    case 1:
                        JOptionPane.showMessageDialog(this,"Impossible car des employés sont assignés à ce bureau : "+liste,"Erreur",JOptionPane.INFORMATION_MESSAGE);
                        break;
                    case 2:
                        Bureau b = new Bureau(idb, sigle, tel);
                        bdao.delete(b);
                        JOptionPane.showMessageDialog(this,"La suppression à bien été effectuée.","Succès",JOptionPane.INFORMATION_MESSAGE);
                        Fenetre.f.setContentPane(new MenuGestBur());
                        Fenetre.f.repaint();
                        Fenetre.f.revalidate();
                        break;
                }
                DBConnection.closeConnection();
            } catch (SQLException ex) {
                Logger.getLogger(ReadBureau.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btConfActionPerformed

    private void tfIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdKeyTyped
        int l = evt.getKeyChar();
        if(!Character.isDigit(l)){
            evt.consume();
        }
    }//GEN-LAST:event_tfIdKeyTyped

    private void btIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIdActionPerformed
        try {
            String liste = "";
            Connection dbConnect = DBConnection.getConnection();
            if (dbConnect == null) {
                System.exit(1);
            }
            Statement stmt = dbConnect.createStatement();
            ResultSet rs = stmt.executeQuery("select * from bureau order by idbur");
            while(rs.next()){
                liste = liste + "\n" + rs.getInt("IDBUR") + " " + rs.getString("SIGLE");
            }
            JOptionPane.showMessageDialog(this,"Liste des bureaux :" + liste,"Information",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ReadEmploye.class.getName()).log(Level.SEVERE, null, ex);
        }
        DBConnection.closeConnection();
    }//GEN-LAST:event_btIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConf;
    private javax.swing.JButton btId;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfId;
    // End of variables declaration//GEN-END:variables
}
