/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messagerie.GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import messagerie.Message;
import messagerie.DAO.MessageDAO;
import myconnections.DBConnection;

/**
 *
 * @author alanl
 */
public class Mail extends javax.swing.JPanel {

    /**
     * Creates new form Mail
     */
    Statement stmt = null;
    ResultSet rs = null;
    String contenu;
    String dateenvoi = "";
    int id_dest;
    Message m;
    MessageDAO mdao = new MessageDAO();
    int id = MenuEmp.idemp;
    int idmsg;
    String mat_dest;
    public Mail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        tfText = new javax.swing.JTextField();
        lab = new javax.swing.JLabel();
        tfMat = new javax.swing.JTextField();
        btMatricules = new javax.swing.JButton();
        btEnv = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setBackground(new java.awt.Color(0, 0, 204));
        setLayout(new java.awt.GridLayout(6, 1, 20, 20));

        tfText.setBackground(new java.awt.Color(255, 255, 255));
        tfText.setForeground(new java.awt.Color(0, 0, 0));
        tfText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfText.setText("Ecrivez votre message...");
        add(tfText);

        lab.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lab.setForeground(new java.awt.Color(255, 255, 255));
        lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab.setText("Entrez ci-dessous le matricule du destinataire :");
        add(lab);

        tfMat.setBackground(new java.awt.Color(255, 255, 255));
        tfMat.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfMat.setForeground(new java.awt.Color(0, 0, 0));
        tfMat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(tfMat);

        btMatricules.setBackground(new java.awt.Color(51, 51, 51));
        btMatricules.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btMatricules.setForeground(new java.awt.Color(255, 255, 255));
        btMatricules.setText("Voir les matricules");
        btMatricules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMatriculesActionPerformed(evt);
            }
        });
        add(btMatricules);

        btEnv.setBackground(new java.awt.Color(51, 51, 51));
        btEnv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btEnv.setForeground(new java.awt.Color(255, 255, 255));
        btEnv.setText("Envoyer");
        btEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnvActionPerformed(evt);
            }
        });
        add(btEnv);

        btRetour.setBackground(new java.awt.Color(51, 51, 51));
        btRetour.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btRetour.setForeground(new java.awt.Color(255, 255, 255));
        btRetour.setText("Annuler");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        add(btRetour);
    }// </editor-fold>//GEN-END:initComponents

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        Fenetre.f.setContentPane(new MenuEmp2());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed

    private void btEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnvActionPerformed
        contenu = tfText.getText();
        mat_dest = tfMat.getText();
        idmsg = 0;
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
           System.exit(1);
        }
        if(!contenu.equals("") && !mat_dest.equals("")){
            try {
                stmt = dbConnect.createStatement();
                rs = stmt.executeQuery("SELECT * FROM message");
                while(rs.next()){
                    idmsg++;
                }
                idmsg++;
                stmt = dbConnect.createStatement();
                rs = stmt.executeQuery("SELECT * FROM employe");
                while(rs.next()){
                    if(rs.getString("MATRICULE").equals(mat_dest)){
                        id_dest = rs.getInt("IDEMP");
                    }
                }
                m = new Message(idmsg,contenu,dateenvoi,id);
                MessageDAO.id_destinataire = id_dest;
                mdao.create(m);
                JOptionPane.showMessageDialog(this,"Message envoyé!","succès",JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(Mail.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(contenu.equals("")){
            JOptionPane.showMessageDialog(this,"Vous n'allez quand même pas envoyer un mail vide ?!","Erreur",JOptionPane.INFORMATION_MESSAGE);
            Fenetre.f.setContentPane(new Mail());
            Fenetre.f.repaint();
            Fenetre.f.revalidate();
        }
        else if(mat_dest.equals("")){
            JOptionPane.showMessageDialog(this,"Il faut entrer un matricule !","Erreur",JOptionPane.INFORMATION_MESSAGE);
            Fenetre.f.setContentPane(new Mail());
            Fenetre.f.repaint();
            Fenetre.f.revalidate();
        }
        DBConnection.closeConnection();
    }//GEN-LAST:event_btEnvActionPerformed

    private void btMatriculesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMatriculesActionPerformed
        String matricules = "";
        try {
            Connection dbConnect = DBConnection.getConnection();
            if (dbConnect == null) {
                System.exit(1);
            }
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from employe order by idemp");
            while(rs.next()){
                matricules = matricules + "\n" + rs.getString("PRENOM") + " " + rs.getString("NOM") + " : " + rs.getString("MATRICULE");
            }
            JOptionPane.showMessageDialog(this,"Liste des matricules : " + matricules,"Information",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Mail.class.getName()).log(Level.SEVERE, null, ex);
        }
        DBConnection.closeConnection();
    }//GEN-LAST:event_btMatriculesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnv;
    private javax.swing.JButton btMatricules;
    private javax.swing.JButton btRetour;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lab;
    private javax.swing.JTextField tfMat;
    private javax.swing.JTextField tfText;
    // End of variables declaration//GEN-END:variables
    
}
