/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messagerie.GUI;

import jaco.mp3.player.MP3Player;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alanl
 */
public class MenuPr extends javax.swing.JPanel {

    /**
     * Creates new form MenuPr
     */
    public MenuPr() {
        initComponents();
    }
    public static final String song = "C:\\Users\\alanl\\Desktop\\closing.mp3";
    static MP3Player mp3player = new MP3Player(new File(song));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labMess = new javax.swing.JLabel();
        btAdmin = new javax.swing.JButton();
        btEmp = new javax.swing.JButton();
        btQuit = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new java.awt.GridLayout(4, 3, 20, 20));

        labMess.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labMess.setForeground(new java.awt.Color(255, 255, 255));
        labMess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labMess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/messagerie/GUI/condor.png"))); // NOI18N
        labMess.setAlignmentX(2.0F);
        add(labMess);

        btAdmin.setBackground(new java.awt.Color(51, 51, 51));
        btAdmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btAdmin.setText("Administrateur");
        btAdmin.setAlignmentX(7.0F);
        btAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btAdmin.setBorderPainted(false);
        btAdmin.setPreferredSize(new java.awt.Dimension(200, 40));
        btAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdminActionPerformed(evt);
            }
        });
        add(btAdmin);

        btEmp.setBackground(new java.awt.Color(51, 51, 51));
        btEmp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btEmp.setForeground(new java.awt.Color(255, 255, 255));
        btEmp.setText("Employé");
        btEmp.setAlignmentX(1.0F);
        btEmp.setPreferredSize(new java.awt.Dimension(200, 40));
        btEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmpActionPerformed(evt);
            }
        });
        add(btEmp);

        btQuit.setBackground(new java.awt.Color(51, 51, 51));
        btQuit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btQuit.setForeground(new java.awt.Color(255, 255, 255));
        btQuit.setText("Quitter");
        btQuit.setPreferredSize(new java.awt.Dimension(200, 40));
        btQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitActionPerformed(evt);
            }
        });
        add(btQuit);
    }// </editor-fold>//GEN-END:initComponents

    private void btQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitActionPerformed
        mp3player.play();
        try {
            Thread.sleep(2300);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuPr.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btQuitActionPerformed

    private void btEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmpActionPerformed
        Fenetre.f.setContentPane(new MenuEmp());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btEmpActionPerformed

    private void btAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdminActionPerformed
        Fenetre.f.setContentPane(new MenuAdmin());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdmin;
    private javax.swing.JButton btEmp;
    private javax.swing.JButton btQuit;
    private javax.swing.JLabel labMess;
    // End of variables declaration//GEN-END:variables
}
