/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messagerie.GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import messagerie.DAO.MessageDAO;
import myconnections.DBConnection;

/**
 *
 * @author alanl
 */
public class MenuEmp extends javax.swing.JPanel {

    /**
     * Creates new form MenuEmp
     */
    Statement stmt = null;
    ResultSet rs = null;
    int flag;
    String nom;
    public static String prenom;
    public static int idemp;
    public MenuEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labConn = new javax.swing.JLabel();
        labMat = new javax.swing.JLabel();
        tfMat = new javax.swing.JTextField();
        btConf = new javax.swing.JButton();
        btRet = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 255));
        setLayout(new java.awt.GridLayout(5, 1, 15, 15));

        labConn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labConn.setForeground(new java.awt.Color(204, 204, 0));
        labConn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labConn.setText("Connexion");
        add(labConn);

        labMat.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labMat.setForeground(new java.awt.Color(204, 204, 0));
        labMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labMat.setText("Entrez votre matricule");
        add(labMat);

        tfMat.setBackground(new java.awt.Color(255, 255, 255));
        tfMat.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfMat.setForeground(new java.awt.Color(0, 0, 0));
        tfMat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(tfMat);

        btConf.setBackground(new java.awt.Color(51, 51, 51));
        btConf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btConf.setForeground(new java.awt.Color(204, 204, 0));
        btConf.setText("Confirmer");
        btConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfActionPerformed(evt);
            }
        });
        add(btConf);

        btRet.setBackground(new java.awt.Color(51, 51, 51));
        btRet.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btRet.setForeground(new java.awt.Color(204, 204, 0));
        btRet.setText("Retour");
        btRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetActionPerformed(evt);
            }
        });
        add(btRet);
    }// </editor-fold>//GEN-END:initComponents

    private void btConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfActionPerformed
        String mat = tfMat.getText();
        Connection dbConnect = DBConnection.getConnection();
       if (dbConnect == null) {
           System.exit(1);
       }
       if (mat != null){
            try {
                stmt = dbConnect.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(MenuEmp.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                rs = stmt.executeQuery("select * from employe");
            } catch (SQLException ex) {
                Logger.getLogger(MenuEmp.class.getName()).log(Level.SEVERE, null, ex);
            }
            flag = 0;
            try {
                while(rs.next()){
                    if(rs.getString("MATRICULE").equals(mat)){
                        flag = 1;
                        nom = rs.getString("NOM");
                        prenom = rs.getString("PRENOM");
                        idemp = rs.getInt("IDEMP");
                        break;
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuEmp.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(flag == 0){
                JOptionPane.showMessageDialog(this,"Le matricule entré n'existe pas !","ERREUR",JOptionPane.INFORMATION_MESSAGE);
                Fenetre.f.setContentPane(new MenuEmp());
                Fenetre.f.repaint();
                Fenetre.f.revalidate();
            }
            else{
                Fenetre.f.setContentPane(new MenuEmp2());
                Fenetre.f.repaint();
                Fenetre.f.revalidate();
            }
       }
       else{
           JOptionPane.showMessageDialog(this,"Le champ est vide !","ERREUR",JOptionPane.INFORMATION_MESSAGE);
           Fenetre.f.setContentPane(new MenuEmp());
           Fenetre.f.repaint();
           Fenetre.f.revalidate();
       }
       DBConnection.closeConnection();
    }//GEN-LAST:event_btConfActionPerformed

    private void btRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetActionPerformed
        Fenetre.f.setContentPane(new MenuPr());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btRetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConf;
    private javax.swing.JButton btRet;
    private javax.swing.JLabel labConn;
    private javax.swing.JLabel labMat;
    private javax.swing.JTextField tfMat;
    // End of variables declaration//GEN-END:variables
}
