/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messagerie.GUI;

import jaco.mp3.player.MP3Player;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
/**
 *
 * @author alanl
 */
public class ModifBureau extends javax.swing.JPanel {

    /**
     * Creates new form ModifBureau
     */
    public static int idBurModif;
    
    public ModifBureau() {
        initComponents();
    }

    public static final String song = "C:\\Users\\alanl\\Desktop\\error.mp3";
    static MP3Player mp3player = new MP3Player(new File(song));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfModif = new javax.swing.JTextField();
        btId = new javax.swing.JButton();
        btConf = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new java.awt.GridLayout(5, 1, 20, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrez l'id du bureau à modifier ");
        add(jLabel1);

        tfModif.setBackground(new java.awt.Color(255, 255, 255));
        tfModif.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfModif.setForeground(new java.awt.Color(0, 0, 0));
        tfModif.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfModif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfModifKeyTyped(evt);
            }
        });
        add(tfModif);

        btId.setBackground(new java.awt.Color(51, 51, 51));
        btId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btId.setForeground(new java.awt.Color(255, 255, 255));
        btId.setText("Voir les id");
        btId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIdActionPerformed(evt);
            }
        });
        add(btId);

        btConf.setBackground(new java.awt.Color(51, 51, 51));
        btConf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btConf.setForeground(new java.awt.Color(255, 255, 255));
        btConf.setText("Confirmer");
        btConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfActionPerformed(evt);
            }
        });
        add(btConf);

        btRetour.setBackground(new java.awt.Color(51, 51, 51));
        btRetour.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btRetour.setForeground(new java.awt.Color(255, 255, 255));
        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        add(btRetour);
    }// </editor-fold>//GEN-END:initComponents

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        Fenetre.f.setContentPane(new MenuGestBur());
        Fenetre.f.repaint();
        Fenetre.f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed

    private void btConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfActionPerformed
        String idModif = tfModif.getText();
        if(idModif.equals("")){
            mp3player.play();
            JOptionPane.showMessageDialog(this,"Vous n'avez entré aucun id !","Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            try {
                idBurModif = Integer.parseInt(idModif);
                ResultSet rs;
                int flag = 0;
                Statement stmt;
                Connection dbConnect = DBConnection.getConnection();
                if (dbConnect == null) {
                    System.exit(1);
                }
                stmt = dbConnect.createStatement();
                rs = stmt.executeQuery("select * from bureau");
                while(rs.next()){
                    if(idBurModif == rs.getInt("IDBUR")){
                        ModifBureau2.id = idBurModif;
                        ModifBureau2.s = rs.getString("SIGLE");
                        ModifBureau2.t = rs.getString("TEL");
                        flag = 1;
                    }
                }
                if(flag == 0){
                    mp3player.play();
                    JOptionPane.showMessageDialog(this,"Cet id ne correspond à aucun bureau !","Erreur",JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    Fenetre.f.setContentPane(new ModifBureau2());
                    Fenetre.f.repaint();
                    Fenetre.f.revalidate();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ReadBureau.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        DBConnection.closeConnection();
    }//GEN-LAST:event_btConfActionPerformed

    private void tfModifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModifKeyTyped
        int l = evt.getKeyChar();
        if(!Character.isDigit(l)){
            evt.consume();
        }
    }//GEN-LAST:event_tfModifKeyTyped

    private void btIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIdActionPerformed
        try {
            String liste = "";
            Connection dbConnect = DBConnection.getConnection();
            if (dbConnect == null) {
                System.exit(1);
            }
            Statement stmt = dbConnect.createStatement();
            ResultSet rs = stmt.executeQuery("select * from bureau order by idbur");
            while(rs.next()){
                liste = liste + "\n" + rs.getInt("IDBUR") + " " + rs.getString("SIGLE");
            }
            JOptionPane.showMessageDialog(this,"Liste des bureaux :" + liste,"Information",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ReadEmploye.class.getName()).log(Level.SEVERE, null, ex);
        }
        DBConnection.closeConnection();
    }//GEN-LAST:event_btIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConf;
    private javax.swing.JButton btId;
    private javax.swing.JButton btRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfModif;
    // End of variables declaration//GEN-END:variables
}
